
# Configuration for CodeCov
codecov:
  max_report_age: off
  require_ci_to_pass: no
  notify:
    require_ci_to_pass: no
    wait_for_ci: false
fixes:
  - "/__w/vsag/::/"

coverage:
  precision: 2
  round: down
  range: "90...100"

  status:
    project:
      default:
        target: 90%
        threshold: 0%
    patch:
      default:
        target: 80%
        threshold: 0%
        if_ci_failed: error

comment:
  layout: "header, diff, flags, components, footer"
  behavior: default
  require_changes: false
  branches:
    - main

component_management:
  default_rules:
    statuses:
      - type: project
        target: auto
        threshold: 1
        branches:
          - "!main"
  individual_components:  # in alphabetical
    - component_id: module_common
      name: common
      paths:
        - src/*
    - component_id: module_datacell
      name: datacell
      paths:
        - src/data_cell/**
        - src/io/**
        - src/quantization/**
    - component_id: module_index
      name: index
      paths:
        - src/index/**
        - src/algorithm/**
        - extern/diskann/**
    - component_id: module_simd
      name: simd
      paths:
        - src/simd/**
