# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Bug Fixes
      labels:
        - kind/bug
    - title: New Features
      labels:
        - kind/feature
    - title: Improvements
      labels:
        - kind/improvement
    - title: Other Changes
      labels:
        - "*"
