version: 2.1

workflows:
  pull-request-workflow:
    jobs:
      - pull-request-check:
          filters:
            branches:
              ignore:
                - main
      - pull-request-check-aarch64:
          filters:
            branches:
              ignore:
                - main
  main-branch-workflow:
    jobs:
      - main-branch-check:
          filters:
            branches:
              only:
                - main
      - main-branch-check-aarch64:
          filters:
            branches:
              only:
                - main

jobs:
  pull-request-check:
    docker:
      - image: vsaglib/vsag:ci-x86
    resource_class: medium+
    steps:
      - checkout
      - restore_cache:
          keys:
            - fork-cache-{{ checksum "CMakeLists.txt" }}-{{ checksum ".circleci/fresh_ci_cache.commit" }}
      - run: make debug
      - save_cache:
          key: fork-cache-{{ checksum "CMakeLists.txt" }}-{{ checksum ".circleci/fresh_ci_cache.commit" }}
          paths:
            - ./build
      - run:
          command: make test_parallel
          no_output_timeout: 15m

  pull-request-check-aarch64:
    docker:
      - image: ubuntu:22.04
    resource_class: arm.medium
    steps:
      - checkout
      - run: bash scripts/deps/install_deps_ubuntu.sh
      - restore_cache:
          keys:
            - fork-cache-arm-{{ checksum "CMakeLists.txt" }}-{{ checksum ".circleci/fresh_ci_cache.commit" }}
      - run: make debug
      - save_cache:
          key: fork-cache-arm-{{ checksum "CMakeLists.txt" }}-{{ checksum ".circleci/fresh_ci_cache.commit" }}
          paths:
            - ./build
      - run:
          command: make test_parallel
          no_output_timeout: 15m

  main-branch-check:
    docker:
      - image: vsaglib/vsag:ci-x86
    resource_class: medium+
    steps:
      - checkout
      - restore_cache:
          keys:
            - main-ccache-{{ checksum "CMakeLists.txt" }}-{{ checksum ".circleci/fresh_ci_cache.commit" }}
      - run: make debug
      - save_cache:
          key: main-ccache-{{ checksum "CMakeLists.txt" }}-{{ checksum ".circleci/fresh_ci_cache.commit" }}
          paths:
            - ./build
      - run:
          command: make test_parallel
          no_output_timeout: 15m

  main-branch-check-aarch64:
    docker:
      - image: ubuntu:22.04
    resource_class: arm.medium
    steps:
      - checkout
      - run: bash scripts/deps/install_deps_ubuntu.sh
      - restore_cache:
          keys:
            - main-ccache-arm-{{ checksum "CMakeLists.txt" }}-{{ checksum ".circleci/fresh_ci_cache.commit" }}
      - run: make debug
      - save_cache:
          key: main-ccache-arm-{{ checksum "CMakeLists.txt" }}-{{ checksum ".circleci/fresh_ci_cache.commit" }}
          paths:
            - ./build
      - run:
          command: make test_parallel
          no_output_timeout: 15m

