
cmake_minimum_required(VERSION 3.15)

set(command "cmake;-DCMAKE_INSTALL_PREFIX=/usr/local;-DCMAKE_CXX_COMPILER=/usr/bin/c++;-DCMAKE_C_COMPILER=/usr/bin/cc;-DCMAKE_POSITION_INDEPENDENT_CODE=ON;-DCMAKE_CXX_FLAGS=-g -Ofast -fPIC;-DCMAKE_C_FLAGS=-g -Ofast -fPIC;-DCMAKE_EXE_LINKER_FLAGS=-static-libstdc++;-DCMAKE_SHARED_LINKER_FLAGS=-static-libstdc++;-DCMAKE_INCLUDE_PATH=/usr/local/include;-DCMAKE_LIBRARY_PATH=/usr/local/lib:/opt/alibaba-cloud-compiler/lib64;-DHDF5_ENABLE_NONSTANDARD_FEATURE_FLOAT16=OFF;-DCMAKE_INSTALL_PREFIX=/root/vsag-hgraph-mci-companion/build-release-mci-add/hdf5/install;-DHDF5_BUILD_CPP_LIB=ON;-S.;-Bbuild")
set(log_merged "")
set(log_output_on_failure "")
set(stdout_log "/root/vsag-hgraph-mci-companion/build-release-mci-add/.vsag-build-info/hdf5-configure-out.log")
set(stderr_log "/root/vsag-hgraph-mci-companion/build-release-mci-add/.vsag-build-info/hdf5-configure-err.log")
execute_process(
  COMMAND ${command}
  RESULT_VARIABLE result
  OUTPUT_FILE "${stdout_log}"
  ERROR_FILE "${stderr_log}"
  )
macro(read_up_to_max_size log_file output_var)
  file(SIZE ${log_file} determined_size)
  set(max_size 10240)
  if (determined_size GREATER max_size)
    math(EXPR seek_position "${determined_size} - ${max_size}")
    file(READ ${log_file} ${output_var} OFFSET ${seek_position})
    set(${output_var} "...skipping to end...\n${${output_var}}")
  else()
    file(READ ${log_file} ${output_var})
  endif()
endmacro()
if(result)
  set(msg "Command failed: ${result}\n")
  foreach(arg IN LISTS command)
    set(msg "${msg} '${arg}'")
  endforeach()
  if (${log_merged})
    set(msg "${msg}\nSee also\n  ${stderr_log}")
  else()
    set(msg "${msg}\nSee also\n  /root/vsag-hgraph-mci-companion/build-release-mci-add/.vsag-build-info/hdf5-configure-*.log")
  endif()
  if (${log_output_on_failure})
    message(SEND_ERROR "${msg}")
    if (${log_merged})
      read_up_to_max_size("${stderr_log}" error_log_contents)
      message(STATUS "Log output is:\n${error_log_contents}")
    else()
      read_up_to_max_size("${stdout_log}" out_log_contents)
      read_up_to_max_size("${stderr_log}" err_log_contents)
      message(STATUS "stdout output is:\n${out_log_contents}")
      message(STATUS "stderr output is:\n${err_log_contents}")
    endif()
    message(FATAL_ERROR "Stopping after outputting logs.")
  else()
    message(FATAL_ERROR "${msg}")
  endif()
else()
  if(NOT "Unix Makefiles" MATCHES "Ninja")
    set(msg "hdf5 configure command succeeded.  See also /root/vsag-hgraph-mci-companion/build-release-mci-add/.vsag-build-info/hdf5-configure-*.log")
    message(STATUS "${msg}")
  endif()
endif()
