
cmake_minimum_required(VERSION 3.15)

set(command "env;CC=/usr/bin/cc;CXX=/usr/bin/c++;CFLAGS=-g -Ofast -fPIC -D_DEFAULT_SOURCE -D_GNU_SOURCE;CXXFLAGS=-g -Ofast -fPIC -D_DEFAULT_SOURCE -D_GNU_SOURCE;CPPFLAGS=-isystem /usr/local/include;LDFLAGS=-Wl,-rpath=\$\$ORIGIN -L/usr/local/lib -L/usr/local/lib64 -L/usr/lib/x86_64-linux-gnu -static-libstdc++;PATH=/root/.local/bin:/root/.vscode-server/data/User/globalStorage/github.copilot-chat/debugCommand:/root/.vscode-server/data/User/globalStorage/github.copilot-chat/copilotCli:/root/.vscode-server/bin/3c631b164c239e7aeaaae7c626b46c527b361af2/bin/remote-cli:/root/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin;CFLAGS=-g -O2 -fPIC -D_DEFAULT_SOURCE -D_GNU_SOURCE;CXXFLAGS=-g -O2 -fPIC -D_DEFAULT_SOURCE -D_GNU_SOURCE;OMP_NUM_THREADS=1;PATH=/usr/lib/ccache:/root/.local/bin:/root/.vscode-server/data/User/globalStorage/github.copilot-chat/debugCommand:/root/.vscode-server/data/User/globalStorage/github.copilot-chat/copilotCli:/root/.vscode-server/bin/3c631b164c239e7aeaaae7c626b46c527b361af2/bin/remote-cli:/root/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin;LD_LIBRARY_PATH=/opt/alibaba-cloud-compiler/lib64/:;make;USE_THREAD=0;USE_LOCKING=1;DYNAMIC_ARCH=1;NOFORTRAN=1;-j4")
set(log_merged "")
set(log_output_on_failure "")
set(stdout_log "/root/vsag-hgraph-mci-companion/build-release-mci-add/.vsag-build-info/openblas-build-out.log")
set(stderr_log "/root/vsag-hgraph-mci-companion/build-release-mci-add/.vsag-build-info/openblas-build-err.log")
execute_process(
  COMMAND ${command}
  RESULT_VARIABLE result
  OUTPUT_FILE "${stdout_log}"
  ERROR_FILE "${stderr_log}"
  )
macro(read_up_to_max_size log_file output_var)
  file(SIZE ${log_file} determined_size)
  set(max_size 10240)
  if (determined_size GREATER max_size)
    math(EXPR seek_position "${determined_size} - ${max_size}")
    file(READ ${log_file} ${output_var} OFFSET ${seek_position})
    set(${output_var} "...skipping to end...\n${${output_var}}")
  else()
    file(READ ${log_file} ${output_var})
  endif()
endmacro()
if(result)
  set(msg "Command failed: ${result}\n")
  foreach(arg IN LISTS command)
    set(msg "${msg} '${arg}'")
  endforeach()
  if (${log_merged})
    set(msg "${msg}\nSee also\n  ${stderr_log}")
  else()
    set(msg "${msg}\nSee also\n  /root/vsag-hgraph-mci-companion/build-release-mci-add/.vsag-build-info/openblas-build-*.log")
  endif()
  if (${log_output_on_failure})
    message(SEND_ERROR "${msg}")
    if (${log_merged})
      read_up_to_max_size("${stderr_log}" error_log_contents)
      message(STATUS "Log output is:\n${error_log_contents}")
    else()
      read_up_to_max_size("${stdout_log}" out_log_contents)
      read_up_to_max_size("${stderr_log}" err_log_contents)
      message(STATUS "stdout output is:\n${out_log_contents}")
      message(STATUS "stderr output is:\n${err_log_contents}")
    endif()
    message(FATAL_ERROR "Stopping after outputting logs.")
  else()
    message(FATAL_ERROR "${msg}")
  endif()
else()
  if(NOT "Unix Makefiles" MATCHES "Ninja")
    set(msg "openblas build command succeeded.  See also /root/vsag-hgraph-mci-companion/build-release-mci-add/.vsag-build-info/openblas-build-*.log")
    message(STATUS "${msg}")
  endif()
endif()
