
cmake_minimum_required(VERSION ${CMAKE_VERSION}) # this file comes with cmake

set(command "env;PATH=/usr/lib/ccache:/home/runner/work/_temp/ghcca-node/node/bin:/snap/bin:/home/runner/.local/bin:/opt/pipx_bin:/home/runner/.cargo/bin:/home/runner/.config/composer/vendor/bin:/usr/local/.ghcup/bin:/home/runner/.dotnet/tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin;./b2;install;-d0;-j4;--prefix=/home/runner/work/vsag/vsag/build_default/boost/install;--disable-icu;include=/home/runner/work/vsag/vsag/build_default/boost/install/include;linkflags=-L/home/runner/work/vsag/vsag/build_default/boost/install/lib;cxxflags=-fPIC ;runtime-link=static;link=static;variant=release;toolset=gcc")
set(log_merged "")
set(log_output_on_failure "")
set(stdout_log "/home/runner/work/vsag/vsag/build_default/boost/src/boost-stamp/boost-build-out.log")
set(stderr_log "/home/runner/work/vsag/vsag/build_default/boost/src/boost-stamp/boost-build-err.log")
execute_process(
  COMMAND ${command}
  RESULT_VARIABLE result
  OUTPUT_FILE "${stdout_log}"
  ERROR_FILE "${stderr_log}"
)
macro(read_up_to_max_size log_file output_var)
  file(SIZE ${log_file} determined_size)
  set(max_size 10240)
  if (determined_size GREATER max_size)
    math(EXPR seek_position "${determined_size} - ${max_size}")
    file(READ ${log_file} ${output_var} OFFSET ${seek_position})
    set(${output_var} "...skipping to end...\n${${output_var}}")
  else()
    file(READ ${log_file} ${output_var})
  endif()
endmacro()
if(result)
  set(msg "Command failed: ${result}\n")
  foreach(arg IN LISTS command)
    set(msg "${msg} '${arg}'")
  endforeach()
  if (${log_merged})
    set(msg "${msg}\nSee also\n  ${stderr_log}")
  else()
    set(msg "${msg}\nSee also\n  /home/runner/work/vsag/vsag/build_default/boost/src/boost-stamp/boost-build-*.log")
  endif()
  if (${log_output_on_failure})
    message(SEND_ERROR "${msg}")
    if (${log_merged})
      read_up_to_max_size("${stderr_log}" error_log_contents)
      message(STATUS "Log output is:\n${error_log_contents}")
    else()
      read_up_to_max_size("${stdout_log}" out_log_contents)
      read_up_to_max_size("${stderr_log}" err_log_contents)
      message(STATUS "stdout output is:\n${out_log_contents}")
      message(STATUS "stderr output is:\n${err_log_contents}")
    endif()
    message(FATAL_ERROR "Stopping after outputting logs.")
  else()
    message(FATAL_ERROR "${msg}")
  endif()
else()
  if(NOT "Unix Makefiles" MATCHES "Ninja")
    set(msg "boost build command succeeded.  See also /home/runner/work/vsag/vsag/build_default/boost/src/boost-stamp/boost-build-*.log")
    message(STATUS "${msg}")
  endif()
endif()
