name: Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  coverage:
    name: Test Coverage
    runs-on: ubuntu-latest
    container:
      image: vsaglib/vsag:ubuntu
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install lcov_cobertura
          apt-get update
          apt install -y curl jq
      - name: Load Cache
        uses: actions/cache@v4.1.2
        with:
          path: ./build/
          key: build-${{ hashFiles('./CMakeLists.txt') }}-${{ hashFiles('./.circleci/fresh_ci_cache.commit') }}
      - name: Compile
        run: make cov
      - name: Run Test
        run: |
          ./scripts/test_parallel_bg.sh
          ./build/mockimpl/tests_mockimpl -d yes ${UT_FILTER} --allow-running-no-tests ${UT_SHARD}
      - name: Collect Coverage Info
        run: bash scripts/collect_cpp_coverage.sh
      - name: Generate XML
        run: lcov_cobertura coverage.info --output coverage.xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          files: coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
