# .github/workflows/release.yml
name: Create Release

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch to create the release from'
        required: true
        default: 'main'
        type: string
      tag_name:
        description: 'The tag for the new release (e.g., v1.0.0)'
        required: true
        type: string

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0

      - name: Package release assets
        run: |
          echo "Packaging release assets..."
          bash ./scripts/release/dist.sh

      - name: Create GitHub Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          name: ${{ github.event.inputs.tag_name }}
          generate_release_notes: true
          files: dist/*.tar.gz
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
