name: Update Docker Image

on:
  push: # refresh ci container
    paths: [ 'docker/**' ]
  pull_request: # to make sure dockerfile change correctly
    branches: [ 'main' ]
    paths: [ 'docker/**' ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ./docker/Dockerfile.x86
          push: true
          tags: vsaglib/vsag:ci-x86
